export const STATUS_CODE_NOT_FOUND = 404;
export const STATUS_CODE_FORBIDDEN = 403;
export const STATUS_CODE_UNAUTHORIZED = 401;
export const STATUS_CODE_PERMANENT_REDIRECT = 301;
export const STATUS_CODE_TEMP_REDIRECT = 302;
